# Generated by Django 4.2 on 2023-05-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='compositionQuestion_DB',
            fields=[
                ('qno', models.AutoField(primary_key=True, serialize=False)),
                ('translation_description', models.CharField(max_length=500)),
                ('max_translation_marks', models.IntegerField(default=0)),
                ('composition_description', models.CharField(max_length=500)),
                ('max_composition_marks', models.IntegerField(default=0)),
            ],
        ),
    ]
