# Generated by Django 3.2.17 on 2023-06-03 08:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='choiceQuestion_DB',
            fields=[
                ('qno', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('optionA', models.CharField(max_length=100)),
                ('optionB', models.CharField(max_length=100)),
                ('optionC', models.CharField(max_length=100)),
                ('optionD', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=200)),
                ('max_marks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='compositionQuestion_DB',
            fields=[
                ('qno', models.AutoField(primary_key=True, serialize=False)),
                ('translation_description', models.CharField(max_length=500)),
                ('max_translation_marks', models.IntegerField(default=0)),
                ('composition_description', models.CharField(max_length=500)),
                ('max_composition_marks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question_Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qPaperTitle', models.CharField(max_length=100)),
                ('choiceQuestions', models.ManyToManyField(to='questions.choiceQuestion_DB')),
                ('compositionQuestions', models.ManyToManyField(to='questions.compositionQuestion_DB')),
            ],
        ),
        migrations.CreateModel(
            name='StuExam_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.CharField(max_length=100)),
                ('choice_score', models.IntegerField(default=0)),
                ('composition_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('qpaper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question_paper')),
            ],
        ),
        migrations.CreateModel(
            name='Stu_ChoiceQuestion',
            fields=[
                ('choicequestion_db_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.choicequestion_db')),
                ('choice', models.CharField(default='E', max_length=3)),
            ],
            bases=('questions.choicequestion_db',),
        ),
        migrations.CreateModel(
            name='Stu_CompositionQuestion',
            fields=[
                ('compositionquestion_db_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.compositionquestion_db')),
                ('translation_answer', models.CharField(default='', max_length=500)),
                ('composition_answer', models.CharField(default='', max_length=500)),
            ],
            bases=('questions.compositionquestion_db',),
        ),
        migrations.CreateModel(
            name='StuResults_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exams', models.ManyToManyField(to='questions.StuExam_DB')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_marks', models.IntegerField()),
                ('start_time', models.DateTimeField(default=datetime.datetime(2023, 6, 3, 16, 0, 8, 620063))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2023, 6, 3, 16, 0, 8, 620063))),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='questions.question_paper')),
            ],
        ),
        migrations.AddField(
            model_name='stuexam_db',
            name='choice_questions',
            field=models.ManyToManyField(to='questions.Stu_ChoiceQuestion'),
        ),
        migrations.AddField(
            model_name='stuexam_db',
            name='composition_questions',
            field=models.ManyToManyField(to='questions.Stu_CompositionQuestion'),
        ),
    ]
