# Generated by Django 4.2 on 2023-05-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_compositionquestion_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qPaperTitle', models.CharField(max_length=100)),
                ('choiceQuestions', models.ManyToManyField(to='question.choicequestion_db')),
                ('compositionQuestions', models.ManyToManyField(to='question.compositionquestion_db')),
            ],
        ),
    ]
