# Generated by Django 4.2 on 2023-05-24 10:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_question_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_marks', models.IntegerField()),
                ('start_time', models.DateTimeField(default=datetime.datetime(2023, 5, 24, 18, 15, 23, 496295))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2023, 5, 24, 18, 15, 23, 496295))),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='question.question_paper')),
            ],
        ),
    ]
